apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-src-sample-vol
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /C/k8s/php-720-sample/2.src-deploy-disk/storage